import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../lib/AuthContext";

const STANDARD=["Novo","Em negociação","Orçamento enviado","Aguardando cliente","Fechado"];

export default function EtapasComercialPage(){
 const {company}=useAuth();const [stages,setStages]=useState([]);const [error,setError]=useState("");
 async function load(){if(!company?.id)return;const {data,error:e}=await supabase.from("opportunity_stages").select("id,name,sort_order").eq("company_id",company.id).order("sort_order");if(e)setError(e.message);setStages(data||[])}
 useEffect(()=>{load()},[company?.id]);
 return <div style={S.page}><header style={S.header}><div style={S.eyebrow}>CONFIGURAÇÃO COMERCIAL</div><h1 style={S.title}>Etapas do processo comercial</h1><p style={S.subtitle}>O ProdOS usa um fluxo comercial simples para o vendedor acompanhar a oportunidade sem transformar o CRM em uma rotina burocrática.</p></header>{error&&<div style={S.error}>{error}</div>}<section style={S.panel}><div style={S.intro}><strong>Fluxo padrão do ProdOS</strong><span>As etapas abaixo organizam a negociação. Produtos, preços, margem e conversão para orçamento ficam dentro da oportunidade.</span></div><div style={S.flow}>{STANDARD.map((name,i)=><div key={name} style={S.flowItem}><div style={S.number}>{i+1}</div><strong>{name}</strong>{i<STANDARD.length-1&&<b>→</b>}</div>)}</div><div style={S.note}><strong>Importante:</strong> “Fechado” representa a negociação comercial concluída. A venda continua no módulo Comercial, onde o orçamento e o pedido são formalizados.</div></section><section style={S.panel}><h2 style={S.sectionTitle}>Etapas cadastradas na empresa</h2>{stages.length?<div style={S.table}><div style={S.rowHead}><span>Ordem</span><span>Etapa</span><span>Status</span></div>{stages.map((s,i)=><div style={S.row} key={s.id}><span>{i+1}</span><strong>{s.name}</strong><span style={S.badge}>{STANDARD.includes(s.name)?"Padrão":"Personalizada"}</span></div>)}</div>:<div style={S.empty}>Nenhuma etapa encontrada. O fluxo padrão será criado automaticamente pelo sistema.</div>}</section></div>;
}
const S={page:{width:"100%",paddingBottom:32},header:{marginBottom:18},eyebrow:{fontSize:10,fontWeight:800,letterSpacing:".12em",color:"var(--amber)",marginBottom:4},title:{fontFamily:"var(--font-display)",fontSize:24,margin:0},subtitle:{color:"var(--text-dim)",fontSize:13,margin:"6px 0 0",maxWidth:760,lineHeight:1.5},panel:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:12,padding:16,marginBottom:14},intro:{display:"grid",gap:4,marginBottom:16},introSpan:{color:"var(--text-dim)"},flow:{display:"flex",alignItems:"center",gap:8,overflowX:"auto",paddingBottom:6},flowItem:{display:"flex",alignItems:"center",gap:7,whiteSpace:"nowrap",fontSize:12},number:{width:25,height:25,borderRadius:"50%",background:"var(--amber)",color:"#fff",display:"grid",placeItems:"center",fontWeight:900},note:{marginTop:14,padding:11,borderRadius:9,background:"var(--bg)",border:"1px solid var(--line)",fontSize:12,lineHeight:1.5},sectionTitle:{fontSize:15,margin:"0 0 12px"},table:{border:"1px solid var(--line)",borderRadius:9,overflow:"hidden"},rowHead:{display:"grid",gridTemplateColumns:"80px 1fr 130px",gap:10,padding:"10px 12px",background:"var(--bg)",color:"var(--text-dim)",fontSize:10,fontWeight:800,textTransform:"uppercase"},row:{display:"grid",gridTemplateColumns:"80px 1fr 130px",gap:10,padding:"11px 12px",borderTop:"1px solid var(--line)",fontSize:12,alignItems:"center"},badge:{justifySelf:"start",fontSize:9,fontWeight:800,border:"1px solid var(--line)",borderRadius:99,padding:"3px 7px"},empty:{padding:20,textAlign:"center",color:"var(--text-dim)"},error:{padding:10,borderRadius:8,border:"1px solid var(--danger)",color:"var(--text)",marginBottom:12}};