import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../lib/AuthContext";

const S={aberto:"Aberto",aguardando_abastecimento:"Aguardando abastecimento",aguardando_separacao:"Aguardando separação",em_separacao:"Em separação",conferindo:"Em conferência",aguardando_faturamento:"Aguardando faturamento",faturado:"Faturado",entregue:"Entregue",cancelado:"Cancelado",parcialmente_faturado:"Parcialmente faturado"};
const money=n=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function PedidosVendaFluxoPage(){
 const {company,profile}=useAuth(); const [orders,setOrders]=useState([]); const [customers,setCustomers]=useState([]); const [products,setProducts]=useState([]); const [selected,setSelected]=useState(""); const [order,setOrder]=useState(null); const [items,setItems]=useState([]); const [stock,setStock]=useState({}); const [requests,setRequests]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [msg,setMsg]=useState("");
 const [newCustomer,setNewCustomer]=useState(""); const [newProduct,setNewProduct]=useState(""); const [qty,setQty]=useState("1"); const [price,setPrice]=useState("");
 async function load(){if(!company?.id)return;setLoading(true);setError("");const [o,c,p,r]=await Promise.all([supabase.from("sales_orders").select("id,code,status,customer_id,total_value,order_date,customers:customer_id(name)").order("order_date",{ascending:false}),supabase.from("customers").select("id,name").order("name"),supabase.from("products").select("id,sku,name,unit,sale_price").eq("active",true).order("name"),supabase.from("sales_order_fulfillment_requests").select("id,sales_order_id,status").order("created_at",{ascending:false})]);setOrders(o.data||[]);setCustomers(c.data||[]);setProducts(p.data||[]);setRequests(r.data||[]);setLoading(false)}
 async function loadOrder(id){setSelected(id);setMsg("");setError("");if(!id){setOrder(null);setItems([]);return}const [{data:o,error:oe},{data:it}]=await Promise.all([supabase.from("sales_orders").select("id,code,status,customer_id,total_value,order_date,customers:customer_id(name,document,address)").eq("id",id).single(),supabase.from("sales_order_items").select("id,product_id,quantity,unit_price,discount_percent,invoiced_quantity,products:product_id(sku,name,unit,sale_price)").eq("sales_order_id",id)]);if(oe){setError(oe.message);return}setOrder(o);setItems(it||[]);const m={};for(const x of it||[]){const {data:a}=await supabase.rpc("available_stock_for_product",{p_product_id:x.product_id,p_exclude_order_id:id});m[x.product_id]=Number(a||0)}setStock(m)}
 useEffect(()=>{load()},[company?.id]);useEffect(()=>{if(selected)loadOrder(selected)},[selected]);
 const req=requests.find(r=>r.sales_order_id===selected); const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.quantity)*Number(i.unit_price)*(1-Number(i.discount_percent||0)/100),0),[items]);
 async function addItem(e){e.preventDefault();if(!newProduct||Number(qty)<=0)return;setSaving(true);setError("");const {error:e1}=await supabase.from("sales_order_items").insert({company_id:company.id,sales_order_id:selected,product_id:newProduct,quantity:Number(qty),unit_price:Number(price||products.find(p=>p.id===newProduct)?.sale_price||0),discount_percent:0});if(e1)setError(e1.message);else{setNewProduct("");setQty("1");setPrice("");await loadOrder(selected)}setSaving(false)}
 async function release(){setSaving(true);setError("");setMsg("");const {data,error:e}=await supabase.rpc("create_sales_order_fulfillment",{p_sales_order_id:selected});if(e)setError(e.message);else{setMsg("Pedido liberado. A reserva e a solicitação de separação foram registradas.");await load();await loadOrder(selected)}setSaving(false)}
 async function sendProduction(){setSaving(true);setError("");const need=items.filter(i=>Number(stock[i.product_id]||0)<Number(i.quantity)-Number(i.invoiced_quantity||0));for(const i of need){const missing=Math.max(0,Number(i.quantity)-Number(i.invoiced_quantity||0)-Number(stock[i.product_id]||0));if(missing>0){const {error:e}=await supabase.from("production_orders").insert({company_id:company.id,code:`OP-${order.code}-${i.products?.sku||i.product_id.slice(0,6)}`,product_id:i.product_id,quantity:missing,sales_order_id:selected,status:"solicitada",requested_by:profile?.id||null});if(e){setError(e.message);break}}}if(!error)setMsg("Necessidade enviada ao PCP para abastecimento do pedido.");await loadOrder(selected);setSaving(false)}
 return <div><header style={st.header}><div><h1 style={st.title}>Pedidos de Venda</h1><p style={st.sub}>Fluxo integrado: pedido → disponibilidade → reserva → separação → conferência → faturamento.</p></div></header>{error&&<div style={st.error}>{error}</div>}{msg&&<div style={st.success}>{msg}</div>}
 <div style={st.toolbar}><input style={st.input} placeholder="Buscar pedido ou cliente" onChange={e=>{const q=e.target.value.toLowerCase();setOrders(v=>v.filter(o=>`${o.code} ${o.customers?.name||""}`.toLowerCase().includes(q)))}}/><span style={st.dim}>{orders.length} pedido(s)</span></div>
 {loading?<p style={st.dim}>Carregando...</p>:<div style={st.list}>{orders.map(o=><button key={o.id} style={st.row} onClick={()=>loadOrder(o.id)}><div><strong>{o.code}</strong><div style={st.dim}>{o.customers?.name||"Sem cliente"}</div></div><div><span style={st.badge}>{S[o.status]||o.status}</span><div style={st.dim}>{money(o.total_value)}</div></div></button>)}</div>}
 {order&&<section style={st.panel}><div style={st.head}><div><span style={st.code}>{order.code}</span><h2 style={st.h2}>{order.customers?.name}</h2><div style={st.dim}>Status: {S[order.status]||order.status}</div></div><div style={st.flow}>{["Pedido","Reserva","Separação","Conferência","Faturamento"].map((x,i)=><span key={x} style={st.step}>{x}</span>)}</div></div>
 <div style={st.grid}><div><span style={st.dim}>Total</span><strong>{money(total)}</strong></div><div><span style={st.dim}>Itens</span><strong>{items.length}</strong></div><div><span style={st.dim}>Disponível</span><strong>{money(items.reduce((s,i)=>s+Math.max(0,Number(stock[i.product_id]||0)),0))}</strong></div><div><span style={st.dim}>Solicitação</span><strong>{req?S[req.status]||req.status:"Não liberado"}</strong></div></div>
 <h3 style={st.h3}>Produtos do pedido</h3><div style={st.tableWrap}><table style={st.table}><thead><tr><th>SKU</th><th>Produto</th><th>Pedido</th><th>Disponível</th><th>Preço</th><th>Total</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.products?.sku}</td><td>{i.products?.name}</td><td>{i.quantity} {i.products?.unit||""}</td><td>{stock[i.product_id]??0}</td><td>{money(i.unit_price)}</td><td>{money(Number(i.quantity)*Number(i.unit_price))}</td></tr>)}</tbody></table></div>
 <form onSubmit={addItem} style={st.add}><select value={newProduct} onChange={e=>{setNewProduct(e.target.value);const p=products.find(x=>x.id===e.target.value);setPrice(String(p?.sale_price??""))}} required><option value="">Adicionar produto...</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select><input type="number" min="0.01" step="0.01" value={qty} onChange={e=>setQty(e.target.value)} /><input type="number" min="0" step="0.01" value={price} placeholder="Preço" onChange={e=>setPrice(e.target.value)} /><button style={st.secondary} disabled={saving}>+ Adicionar</button></form>
 <div style={st.actions}>{!req&&<button style={st.primary} disabled={saving||!items.length} onClick={release}>Liberar para separação</button>}{req?.status==="aguardando_abastecimento"&&<button style={st.primary} disabled={saving} onClick={sendProduction}>Enviar necessidade ao PCP</button>}{req?.status==="aguardando_faturamento"&&<a style={st.link} href={`/notas-fiscais?solicitacao=${req.id}`}>Abrir Faturamento →</a>}</div>
 </section>}</div>}
const st={header:{marginBottom:20},title:{fontFamily:"var(--font-display)",fontSize:22,margin:0},sub:{color:"var(--text-dim)",fontSize:13,marginTop:6},toolbar:{display:"flex",gap:10,alignItems:"center",marginBottom:14},input:{background:"var(--field)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"10px 12px",color:"var(--text)",width:320},dim:{color:"var(--text-dim)",fontSize:12},list:{display:"grid",gap:8},row:{display:"flex",justifyContent:"space-between",alignItems:"center",textAlign:"left",background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:14,cursor:"pointer",color:"var(--text)"},panel:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:18,marginTop:18},head:{display:"flex",justifyContent:"space-between",gap:20},code:{color:"var(--amber)",fontWeight:800,fontSize:11},h2:{margin:"4px 0",fontFamily:"var(--font-display)"},h3:{fontSize:14,margin:"18px 0 10px"},badge:{padding:"4px 9px",border:"1px solid var(--line)",borderRadius:20,fontSize:10,fontWeight:700},flow:{display:"flex",gap:4,flexWrap:"wrap"},step:{padding:"6px 9px",background:"var(--panel-2)",borderRadius:20,fontSize:10},grid:{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,margin:"16px 0"},tableWrap:{overflowX:"auto"},table:{width:"100%",borderCollapse:"collapse",fontSize:12},add:{display:"flex",gap:8,marginTop:12,flexWrap:"wrap"},secondary:{background:"var(--field)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"9px 12px",fontWeight:700},primary:{background:"var(--amber)",color:"#fff",border:0,borderRadius:"var(--radius)",padding:"10px 14px",fontWeight:800},actions:{display:"flex",gap:10,alignItems:"center",marginTop:16},link:{color:"var(--amber)",fontWeight:800,textDecoration:"none"},error:{background:"rgba(192,57,43,.1)",border:"1px solid var(--red)",padding:10,borderRadius:"var(--radius)",color:"var(--red)",marginBottom:12},success:{background:"rgba(22,131,90,.1)",border:"1px solid var(--green)",padding:10,borderRadius:"var(--radius)",marginBottom:12}}
